### PR TITLE
Postgres/Redshift update.

### PR DESCRIPTION
**Pull request by hidekoji**
Updated Doc for PostgreSQL and Redshift

### CODE REVIEW

**Comment by kanaugust** [comment]
Is there any Redshift or PostgreSQL specific parameters, which are not available or not exposed for MySQL, we can set?

**Comment by hidekoji** [comment]
Currently, exposed parameters are same for MySQL, PostgreSQL, and Redshift.

- Hostname
- Port
- Database
- Username
- Password
- # of rows
- query

**Comment by kanaugust** [comment]
Not the exposed parameters, what are the parameters we are not exposing and different from MySQL?

**Comment by hidekoji** [comment]
MySQL: http://www.inside-r.org/packages/cran/RMySQL/docs/mysqlNewConnection
PostgreSQL: http://www.inside-r.org/packages/cran/RPostgreSQL/docs/postgresqlNewConnection

### Postgres Specific parameter

#### forceISOdate

logical indicating whether "set datestyle to ISO" is issued upon connection. Although this is made as an option, the conversion needs to be ISO style for proper conversion of the date datatype.

#### params

actual values that is written as parameters in the statement.

```{r}
postgresqlExecStatement(con, "DELETE FROM $1 WHERE id = $2", c("foo_bar", 1)) 
```


#### identifiers

one or more character strings to be used as identifier in SQL statement

**Pull request merged**
